### ISSUE TITLE
Module parse failed in npm module

### ISSUE THREAD

**Issue by FindJobsHongWei** [nuxy/react-baraja-js#1] opened 2022-09-08 01:45 UTC
When I tried to run the package, this error appeared. 

```
error - ./node_modules/react-baraja-js/src/react-baraja.js
Module parse failed: Unexpected token (52:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   render() {
|     return (
>       <ul id={this.props.id} className="baraja-container" ref="wrapper">
|         {this.props.children.map((Child, index) => {
|           return <li key={index}>{Child}</li>;

```

Comment from a StackedOverflow user
"I'm pretty sure the issue is caused by babel ignoring node_modules. Judging by the number of weekly downloads of the module you are trying to use (1), the author of the module misconfigured it."

**Comment by nuxy** [comment] 2022-11-08 20:24
Without seeing your code I cannot really help much. This works for me on _all web browsers_.

Have you tested the [demo](https://github.com/nuxy/react-baraja-js/tree/master/demo)?

Run the following command and then open `index.html` in your web browser.
```
$ npm run build
```

If this works then there is something wrong with your configuration.

**Comment by nuxy** [comment] 2022-11-09 19:50
Issue not reproducible. Package provides working React implementation.

Closing this issue.

**Closed as not planned by nuxy** 2022-11-09 19:50 UTC
Labels: question, wontfix
